# MIT License

# Copyright (c) 2024 EASE lab

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "3.3"
services:
  rnn-serving-python:
    image: pourpourr/rnn-serving-python:latest
    container_name: rnn-serving-python
    entrypoint:
      - python3
      - /app/server.py
      - --addr=0.0.0.0
      - --port=50051
      - --default_language=French
      - --num_strings=15
    ports:
      - target: 50051
  relay:
    image: pourpourr/relay:latest
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50000
      - --function-endpoint-url=rnn-serving-python
      - --function-endpoint-port=50051
      - --function-name=rnn-serving-python
      - --value=French
      - --generator=random
      - --lowerBound=10
      - --upperBound=15
    ports:
        - published: 50000
          target: 50000