# MIT License

# Copyright (c) 2022 EASE lab

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

version: "3.9"
services:

  ## Function ###
  recommendation:
    image: pourpourr/hotel-app-recommendation:latest
    container_name: recommendation
    networks:
      - cassandra
    entrypoint:
      - /app/server
      - --url=0.0.0.0
      - --port=8083
      - --db_addr=database:9042
    ports:
      - target: 8083
        # published: 50000
    depends_on:
      - database


  database:
    # image:  pourpourr/cassandra:latest
    image:  pourpourr/cassandra:latest
    # image: cloudsuitetest/cassandra:3.11.6
    container_name: db
    networks:
      - cassandra
    hostname: cassandra
    ports: 
      - 9042:9042    
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
        interval: 120s
        timeout: 120s
        retries: 5


  ## Utils ##
  relay:
    image: pourpourr/relay:latest
    container_name: relay
    networks:
      - cassandra
    entrypoint:
      - /app/server
      - --addr=0.0.0.0:50000
      - --function-endpoint-url=recommendation
      - --function-endpoint-port=8083
      - --function-name=recommendation
      - --value="dis"
    ports:
        - published: 50000
          target: 50000
    depends_on:
      - recommendation

networks:
    cassandra:
      driver: bridge       